version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      DATABASE_URL: postgresql://idle:idle@pg:5432/idle?chema=idle&sslmode=prefer

  pg:
    container_name: pg
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: idle
      POSTGRES_USER: idle
      POSTGRES_DB: idle
    ports:
      - '5432:5432'

volumes:
  postgres-data:
